// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7QyhVhDbeN3hDfzaUMwbxh2YirVdf-IQ',
    appId: '1:1035265787371:web:e318cd2776507486bd05ae',
    messagingSenderId: '1035265787371',
    projectId: 'authapp-e5541',
    authDomain: 'authapp-e5541.firebaseapp.com',
    storageBucket: 'authapp-e5541.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkIZz_I9UPwUx3A3XPPloc7NxqyqS9AVM',
    appId: '1:1035265787371:android:f95b31a3ab5d3411bd05ae',
    messagingSenderId: '1035265787371',
    projectId: 'authapp-e5541',
    storageBucket: 'authapp-e5541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7EEZJAd8RW6FGHT6hYQXINtxx_Lp_gs',
    appId: '1:1035265787371:ios:8457dd5602f71ec5bd05ae',
    messagingSenderId: '1035265787371',
    projectId: 'authapp-e5541',
    storageBucket: 'authapp-e5541.appspot.com',
    iosClientId: '1035265787371-r35l822fv2ef34fahielnq6hohgf15dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.authapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh7EEZJAd8RW6FGHT6hYQXINtxx_Lp_gs',
    appId: '1:1035265787371:ios:8457dd5602f71ec5bd05ae',
    messagingSenderId: '1035265787371',
    projectId: 'authapp-e5541',
    storageBucket: 'authapp-e5541.appspot.com',
    iosClientId: '1035265787371-r35l822fv2ef34fahielnq6hohgf15dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.authapp',
  );
}
